services:
  db: 
    image: "mdillon/postgis:11-alpine"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: siteDockerise.web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - db